SellPhoneMvcUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SellPhoneMvcUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartRepository _cartRepository;
        public CartController(ICartRepository cartRepository) {
            _cartRepository = cartRepository;
        }

        public async Task<IActionResult> AddItem(int productId, int qty = 1, int redirect = 0)
        {
            var cartCount = await _cartRepository.AddItemAsync(productId, qty);
            if (redirect == 0)
                return Ok(cartCount);
            return RedirectToAction("GetUserCart");
        }

        public async Task<IActionResult> RemoveItem(int productId, int qty=1, bool removeAll=false)
        {
            var cartCount = await _cartRepository.RemoveItemAsync(productId, qty, removeAll);
            return RedirectToAction("GetUserCart");
        }

        public async Task<IActionResult> GetUserCart()
        {
            var cart = await _cartRepository.GetUserCart();
            return View(cart);
        }

        public async Task<IActionResult> GetTotalItemInCart()
        {
            int total = await _cartRepository.GetCartItemCountAsync();
            return Ok(total);
        }

        public async Task<IActionResult> Checkout()
        {
            bool isCheckOut = await _cartRepository.DoCheckout();
            if (!isCheckOut)
                throw new Exception("Somthing happen in server side");
            return RedirectToAction("Index", "Home");
        }
    }
}

SellPhoneMvcUI/Controllers/UserOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SellPhoneMvcUI.Controllers
{
    [Authorize]
    public class UserOrderController : Controller
    {
        private readonly IUserOrderRepository _userOrderRepository;

        public UserOrderController(IUserOrderRepository userOrderRepository)
        {
            _userOrderRepository = userOrderRepository;
        }

        public async Task<IActionResult> UserOrders()
        {
            var orders = await _userOrderRepository.UserOrders();
            return View(orders);
        }
    }
}

SellPhoneMvcUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-theme="lemonade">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SellPhoneMvcUI</title>
@*     <script type="importmap"></script> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/product.css">

    <script type="importmap"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand text-white  " asp-area="" asp-controller="Home" asp-action="Index">SAMSUNG</a>
                <button class="navbar-toggler shadow-none border-0 ms-auto" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
                        <li class="nav-item">
                            <a class="nav-link mx-2 text-white" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-2 text-white" asp-area="" asp-controller="Home" asp-action="listProduct">PRODUCT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-2 text-white" asp-area="" asp-controller="UserOrder" asp-action="UserOrders">ORDERS</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="GetUserCart">
                                CART
                            </a>
                        </li>
                        </li>
                        <li class="nav-item mx-2 ">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="contact">CONTACT</a>
                        </li>
                    </ul>
@*                     <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-light bi bi-search" type="submit"></button>
                    </form> *@
                    <partial class="nav-item mx-2" name="_loginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3 flex-grow-1">
            @RenderBody()
        </main>
    </div>
    <footer class="mt-auto bg-dark text-white py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-5 offset-md-1 mb-3">
                    <form>
                        <h5>Subscribe to our newsletter</h5>
                        <p>Monthly digest of what's new and exciting from us.</p>
                    </form>
                </div>
                <div class="col-6 col-md-2 mb-3">
                    <h5>Section</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5>Section</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5>Section</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                    </ul>
                </div>


            </div>
        </div>
    </footer>
    <script>
        $(document).ready(function () {
            $("#footerYear").html(new Date().getFullYear());
            async function loadCartCount() {
                try {
                    var response = await $.ajax({
                        url: "/Cart/GetTotalItemInCart",
                        method: "GET"
                    });
                    console.log("Response total item:", response);

                    $(".cartCount").html(response);

                    if (response > 0) {
                        $(".cartCount").show();
                    } else {
                        $(".cartCount").html(0);
                    }
                } catch (err) {
                    console.error("Error loading cart count:", err);
                    $(".cartCount").html(0);
                }
            }
            loadCartCount();
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>